// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktwslyqainjwdajrgdss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0d3NseXFhaW5qd2RhanJnZHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTk1ODIsImV4cCI6MjA3MTI5NTU4Mn0.3ayVbLz5EfISzQHpTNpvldIVkYAS_2LymJabR8t5mjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});